YOUTUBE_API_KEY = 'AIzaSyB6_fA2Tk9CGAPz9SsPzTk4VW1ZIgPuJRY'
HAMZA_CHANNEL_ID = 'UCWsslCoN3b_wBaFVWK_ye_A'
JSON_FILE_PATH = 'channel_videos.json'
OPENAI_API_KEY = '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'